AWSTemplateFormatVersion: 2010-09-09
Description: "Cloudformation Demo"

Parameters: 
  Environment: 
    Description: Environment Name
    Type: String

Resources:
  sqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub poc-cloudformation-queue${Environment}

  lambdaFunctioniamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: "poc-cloudformation-lambda-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Action: 
                    - "logs:CreateLogGroup"
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                  Resource: "*"

        - PolicyName: "allow-sqs-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Action: 
                    - "sqs:ReceiveMessage"
                    - "sqs:DeleteMessage"
                    - "sqs:GetQueueAttributes"
                    - "sqs:ChangeMessageVisibility"
                  Resource: !GetAtt sqsQueue.Arn                

  lambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: "Cloudformation Poc Lambda"
      FunctionName: !Sub poc-cloudformation${Environment}
      Handler: main::main.Function::FunctionHandler
      MemorySize: 128
      Role: !GetAtt lambdaFunctioniamRole.Arn
      Runtime: dotnet6
      Timeout: 30
      Environment:
        Variables:
          key1: value1 # A map of key-value pairs that the Lambda function can access
      Code:
        S3Bucket: poc-cloudformation-packages-wc
        S3Key: lambda.zip
      Tags:
        - Key: keyname
          Value: value

  LambdaFunctionEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn: !GetAtt sqsQueue.Arn
      FunctionName: !GetAtt lambdaFunction.Arn