name: Cloudformation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Publish
      run: dotnet publish --no-self-contained --runtime linux-x64 --configuration Release --output ./artifact/publish   ./src/main/main.csproj

    - name: Install zip
      uses: montudor/action-zip@v1

    - name: Zip output
      run: zip -qq -r ../lambda.zip .
      working-directory: artifact/publish
      
    - name: Copy Cloudformation Template
      run: cp ./deployment.yaml ./artifact/deployment.yaml
      
    - uses: actions/upload-artifact@v3
      with:
        name: lambda
        path: ./artifact
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
        
    - name: Upload to S3
      run: aws s3 cp ./artifact/lambda.zip s3://poc-cloudformation-packages-wc
      
  test-deploy:
    runs-on: ubuntu-latest
    environment: Test
    needs: build
    
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: lambda
          path: artifact
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: poc_cloudformation
          template: artifact/deployment.yaml
          parameter-overrides: "Environment=-Test"
    
    
    
